[package]
name = "OpEn_solve"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
optimization_engine = "*"
libc = "*"

[lib]
crate-type=["staticlib"]
name = "OpEn_solve"